const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Platform,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground2: 0},
	{nama_diri_sendiriremovebgpreview: 0},
	{nama_dkvremovebgpreview: 0},
	{segitiga_kuning_atasremovebgpreview: 0},
	{segitiga_merahremovebgpreview: 0},
	{kuningBawah: 0},
	{logoDkv: 0},
	{logosmkn4prob: 0},
	{Sprite: 0},
	{Touch: 0},
	{TiledBackground: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{Sprite2: 0},
	{TiledBackground5: 0},
	{Sprite3: 0},
	{DragDrop: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Platform: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Sprite14: 0},
	{Sprite18: 0}
];

self.InstanceType = {
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	nama_diri_sendiriremovebgpreview: class extends self.ISpriteInstance {},
	nama_dkvremovebgpreview: class extends self.ISpriteInstance {},
	segitiga_kuning_atasremovebgpreview: class extends self.ISpriteInstance {},
	segitiga_merahremovebgpreview: class extends self.ISpriteInstance {},
	kuningBawah: class extends self.ISpriteInstance {},
	logoDkv: class extends self.ISpriteInstance {},
	logosmkn4prob: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {}
}